//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySale
    {
        public string Staff { get; set; }
        public string Customer { get; set; }
        public string Medicine { get; set; }
        public int Potency_mg { get; set; }
        public int Quantity { get; set; }
        public System.DateTime SoldON { get; set; }
    }
}
