//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiredMedicine
    {
        public string Medicine_Name { get; set; }
        public int Potency_in_mg { get; set; }
        public System.DateTime ExpiryDate { get; set; }
    }
}
