//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicinePotency
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicinePotency()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int MedPot_Id { get; set; }
        public int Medicine_Id { get; set; }
        public int Potency_Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> NoOfItem { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual Potency Potency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
