//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Sold_Id { get; set; }
        public int NoOfItem { get; set; }
        public System.DateTime Date { get; set; }
        public int Staff_Id { get; set; }
        public int Customer_Id { get; set; }
        public int MedPot_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual MedicinePotency MedicinePotency { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
