//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Stock_Id { get; set; }
        public int Medicine_Id { get; set; }
        public int NoOfItems { get; set; }
        public int Potency_Id { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual MedicinePotency MedicinePotency { get; set; }
    }
}
